name: CI practice

on:
  push:
    branches: ["master"]
  # Can be trigger manually
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Get Codebase
      - uses: actions/checkout@v2
      # Setup python env
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"
      # Upgrade pip
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      # Linter
      # # stop the build if there are Python syntax errors or undefined names
      # flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      # # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
      # flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 .
      # Security linter
      - name: Security Lint with bandit
        run: |
          pip install bandit
          bandit -r --skip B101 .
      # Install dependencies
      - name: Install dependencies
        run: |
          pip install pipenv pytest
          pipenv install --dev --system
      # Test
      - name: Test with pytest
        run: pytest

      # Dockerfile linter: Hadolint
      - name: Security Lint with Hadolint
        run: |
          wget --quiet -O hadolint https://github.com/hadolint/hadolint/releases/download/$VERSION/hadolint-Linux-x86_64
          chmod +x hadolint
          ./hadolint Dockerfile --verbose --failure-threshold error
        env:
          VERSION: v2.8.0
      # Build container image
      - name: Build image
        run: |
          pipenv lock -r > requirements.txt
          docker build . --file Dockerfile --tag muller-image:$(date +%s)
