name: CI practice


on:
  push:
    branches: [ $default-branch ]
  workflow_dispatch:


jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: "3.7"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv flake8 pytest
        pipenv install --dev --system 

    - name: Test with pytest
      run: |
        pytest
